# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0000_get_requester_ratings_fn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='modulebatchfile',
            unique_together=set([('batch_file', 'module')]),
        ),
    ]
