# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 22:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0000_hstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesterinputfile',
            name='first_row',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requesterinputfile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesterinputfile',
            name='file',
            field=models.FileField(upload_to=b'project_files/'),
        ),
    ]
