# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0000_worker_qualifications'),
        ('crowdsourcing', '0000_get_worker_ratings_fn'),
    ]

    operations = [
    ]
