# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 22:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0001_auto_20151207_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'project_files/')),
                ('deleted', models.BooleanField(default=False)),
                ('format', models.CharField(max_length=8)),
                ('number_of_rows', models.IntegerField(default=0, null=True)),
                ('column_headers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('first_row', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RequesterInputFile',
        ),
    ]
