# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0001_merge_20170726_2309'),
        ('crowdsourcing', '0000_update_topic_id_data'),
    ]

    operations = [
    ]
