# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0001_auto_20151210_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.UserProfile')
        ),
    ]
