# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0002_auto_20151207_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchfile',
            name='format',
            field=models.CharField(default=b'csv', max_length=8),
        ),
        migrations.AlterField(
            model_name='batchfile',
            name='number_of_rows',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
