# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0000_get_worker_ratings_fn'),
        ('crowdsourcing', '0002_template_owner'),
    ]

    operations = [
    ]
