# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0003_taskworker_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='group_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskworker',
            name='group_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='group_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
