# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0003_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateitem',
            name='role',
            field=models.CharField(default=b'display', max_length=16),
        ),
    ]
