# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0003_auto_20151207_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfile',
            name='hash_sha512',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
