# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0004_auto_20170731_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWorkerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(db_index=True, null=True)),
                ('task_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='crowdsourcing.TaskWorker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
