# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0000_get_min_ratings_fn'),
        ('crowdsourcing', '0004_templateitem_role'),
    ]

    operations = [
    ]
