# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0005_auto_20151207_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfile',
            name='name',
            field=models.CharField(default='csv', max_length=256),
            preserve_default=False,
        ),
    ]
