# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='published_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_owner', to='crowdsourcing.Requester'),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.IntegerField(choices=[(1, b'Saved'), (2, b'Published'), (3, b'In Progress'), (4, b'Completed'), (5, b'Paused')], default=1),
        ),
    ]
