# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 22:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0005_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateitem',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='id_string',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='label',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='values',
        ),
        migrations.AddField(
            model_name='templateitem',
            name='aux_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='name',
            field=models.CharField(default=b'', max_length=128),
        ),
    ]
