# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0005_taskworkersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publish_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, b'Draft'), (2, b'Published'), (3, b'In Progress'), (4, b'Completed'), (5, b'Paused'), (6, b'Rejected'), (7, b'Archived')], default=1),
        ),
    ]
