# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0006_batchfile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleBatchFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.BatchFile')),
            ],
        ),
        migrations.RenameField(
            model_name='module',
            old_name='template',
            new_name='templates',
        ),
        migrations.AddField(
            model_name='modulebatchfile',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='batch_files',
            field=models.ManyToManyField(through='crowdsourcing.ModuleBatchFile', to='crowdsourcing.BatchFile'),
        ),
    ]
