# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0006_auto_20151214_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateitem',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
