# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 22:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0006_auto_20170811_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='aux_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='ready_for_launch',
            field=models.NullBooleanField(),
        ),
    ]
