# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0007_templateitem_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateitem',
            name='sub_type',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
