# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0007_auto_20170817_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworker',
            name='auto_approved',
            field=models.BooleanField(default=False),
        ),
    ]
