# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 23:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0008_templateitem_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskworkerresult',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
