# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0008_taskworker_auto_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_boomerang',
            field=models.BooleanField(default=True),
        ),
    ]
