# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0009_templateitem_predecessor'),
        ('crowdsourcing', '0009_project_enable_boomerang'),
    ]

    operations = [
    ]
