# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0006_auto_20151219_0501'),
        ('crowdsourcing', '0009_auto_20151216_2359'),
    ]

    operations = [
    ]
