# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0013_auto_20151221_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(1, b'Sent'), (2, b'Delivered'), (3, b'Read')], default=1),
        ),
        migrations.AlterField(
            model_name='paypalflow',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows_received', to='crowdsourcing.FinancialAccount'),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='role',
            field=models.CharField(choices=[(b'display', b'Display'), (b'input', b'Input')], default=b'display', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='crowdsourcing.FinancialAccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to='crowdsourcing.FinancialAccount'),
        ),
    ]
