# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0012_projectpreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateitem',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
