# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 21:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0013_auto_20171212_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(max_length=256)),
                ('content_type', models.CharField(default=b'application/json', max_length=64)),
                ('event', models.CharField(db_index=True, max_length=16)),
                ('object', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('retry_count', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('secret', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='webhook',
            index_together=set([('event', 'object')]),
        ),
    ]
