# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdsourcing', '0014_auto_20180109_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_hooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
