# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0063_delete_requesterranking'),
        ('crowdsourcing', '0014_auto_20151224_0134'),
    ]

    operations = [
    ]
