# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0064_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerrequesterrating',
            name='project',
        ),
    ]
