# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0012_auto_20160107_0521'),
        ('crowdsourcing', '0065_remove_workerrequesterrating_project'),
    ]

    operations = [
    ]
