# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0066_merge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskworker',
            unique_together=set([('task', 'worker')]),
        ),
    ]
