# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0067_auto_20160112_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ethnicity',
            field=models.CharField(choices=[(b'white', b'White'), (b'hispanic', b'Hispanic'), (b'black', b'Black'), (b'islander', b'Native Hawaiian or Other Pacific Islander'), (b'indian', b'Indian'), (b'asian', b'Asian'), (b'native', b'Native American or Alaska Native')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other')], max_length=1),
        ),
    ]
