# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0071_auto_20160218_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='auto_skip',
            field=models.BooleanField(default=True),
        ),
    ]
