# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0067_auto_20160112_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='scope',
            field=models.CharField(default=b'daemo', max_length=32),
        ),
    ]
