# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0068_userpreferences_auto_skip'),
    ]

    operations = [
    	migrations.RenameField(
    		model_name='userpreferences', 
    		old_name='auto_skip', 
    		new_name='auto_accept')
    ]
