# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0068_auto_20160216_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[(b'white', b'White'), (b'hispanic', b'Hispanic'), (b'black', b'Black'), (b'islander', b'Native Hawaiian or Other Pacific Islander'), (b'indian', b'Indian'), (b'asian', b'Asian'), (b'native', b'Native American or Alaska Native')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
