# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0068_worker_scope'),
        ('crowdsourcing', '0069_auto_20160201_1815'),
    ]

    operations = [
    ]
