# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0069_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
