# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0070_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Currency'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Language'),
        ),
    ]
