# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0070_auto_20160224_1140'),
        ('crowdsourcing', '0071_auto_20160306_1510'),
    ]

    operations = [
    ]
