# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0072_module_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default=b'Untitled Project', error_messages={b'required': b'Please enter the milestone name!'}, max_length=128),
        ),
    ]
