# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0072_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post_mturk',
            field=models.BooleanField(default=False),
        ),
    ]
