# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0070_auto_20160222_1848'),
        ('crowdsourcing', '0073_project_post_mturk'),
    ]

    operations = [
    ]
