# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0074_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paypal_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='conversationrecipient',
            name='status',
            field=models.SmallIntegerField(choices=[(1, b'Open'), (2, b'Minimized'), (3, b'Closed'), (4, b'Muted')], default=1),
        ),
    ]
