# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0075_auto_20160503_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='worker',
            name='has_guild',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='moving_review_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='num_tasks_post_review',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
