# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0076_auto_20160504_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'In Progress'), (2, b'Submitted')], default=1)),
                ('rating', models.PositiveIntegerField(default=1)),
                ('is_acceptable', models.BooleanField(default=False)),
                ('comment', models.TextField(default=b'', max_length=8192)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_reviews', to='crowdsourcing.Review')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Worker')),
                ('task_worker_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='crowdsourcing.TaskWorkerResult')),
            ],
        ),
    ]
