# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0076_get_min_ratings_fn'),
        ('crowdsourcing', '0073_auto_20160315_1627'),
    ]

    operations = [
    ]
