# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0076_auto_20160504_2128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttemplate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='template',
        ),
        migrations.RemoveField(
            model_name='project',
            name='templates',
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Template'),
        ),
        migrations.DeleteModel(
            name='ProjectTemplate',
        ),
    ]
