# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0000_worker_qualifications'),
        ('crowdsourcing', '0075_auto_20160506_0627'),
        ('crowdsourcing', '0077_merge'),
    ]

    operations = [
    ]
