# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0077_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='created_timestamp',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='moving_review_avg',
            new_name='review_rating_sum',
        ),
        migrations.AddField(
            model_name='review',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='taskworkerresult',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='num_reviews_post_leveling',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='num_reviews_post_review',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Worker'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[(0, b'Pending Assignment'), (1, b'In Progress'), (2, b'Submitted')], default=0),
        ),
    ]
