# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 20:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0078_auto_20160505_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='project',
        ),
        migrations.RemoveField(
            model_name='qualificationitem',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='qualificationitem',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='qualificationitem',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='qualificationitem',
            name='value2',
        ),
        migrations.AddField(
            model_name='project',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Qualification'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='qualificationitem',
            name='expression',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualificationitem',
            name='group',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='qualificationitem',
            name='next_op',
            field=models.CharField(default=b'empty', max_length=16),
        ),
        migrations.AddField(
            model_name='qualificationitem',
            name='position',
            field=models.SmallIntegerField(null=True),
        ),
    ]
