# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0078_auto_20160507_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='task_worker_result',
        ),
        migrations.RemoveField(
            model_name='taskworkerresult',
            name='level',
        ),
        migrations.AddField(
            model_name='review',
            name='task_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='crowdsourcing.TaskWorker'),
            preserve_default=False,
        ),
    ]
