# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0000_get_requester_ratings_fn_updated'),
        ('crowdsourcing', '0000_get_worker_ratings_fn_updated'),
        ('crowdsourcing', '0078_auto_20160601_1755'),
    ]

    operations = [
    ]
