# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 05:21
from __future__ import unicode_literals

from django.db import migrations


def alter_financial_account_type(apps, schema_editor):
    # We can't import the FinancialAccount model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    account = apps.get_model("crowdsourcing", "FinancialAccount")
    financial_accounts = account.objects.all()

    for financial_account in financial_accounts:
        if financial_account.type in ['paypal_deposit', 'requester', 'general']:
            financial_account.type = '2'
            financial_account.save()
        if financial_account.type in ['worker']:
            financial_account.type = '1'
            financial_account.save()


class Migration(migrations.Migration):
    dependencies = [
        ('crowdsourcing', '0080_auto_20160601_1822'),
    ]

    operations = [
        migrations.RunPython(alter_financial_account_type),
    ]
