# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 07:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdsourcing', '0080_auto_20160601_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField(max_length=2048)),
                ('root', models.CharField(max_length=256)),
                ('quota', models.BigIntegerField()),
                ('used_space', models.BigIntegerField()),
                ('assigned_space', models.BigIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(1, b'Sent'), (2, b'Delivered'), (3, b'Read')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reset_key', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        # migrations.RenameModel(
        #     old_name='TemporaryFlowModel',
        #     new_name='DropboxAuth',
        # ),
        # migrations.RenameModel(
        #     old_name='FlowModel',
        #     new_name='GoogleAuth',
        # ),
        # migrations.RenameModel(
        #     old_name='CredentialsModel',
        #     new_name='GoogleCredential',
        # ),
        migrations.RenameModel(
            old_name='RegistrationModel',
            new_name='UserRegistration',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='passwordresetmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='conversationrecipient',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='paypalflow',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='paypalflow',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='published_time',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='projectcategory',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='projectcategory',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='qualificationitem',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='qualificationitem',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='taskworker',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='taskworker',
            old_name='task_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='taskworker',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='taskworkerresult',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='taskworkerresult',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='templateitem',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='templateitem',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='templateitemproperties',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='templateitemproperties',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='usercountry',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usercountry',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userlanguage',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userskill',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userskill',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='userskill',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='created_timestamp',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='batchfile',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='conversationrecipient',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user_source',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user_target',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='role',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='price',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='taskworkerresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='template',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 7, 42, 36, 385210, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 7, 42, 50, 392803, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 7, 43, 2, 432120, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchfile',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='batchfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 7, 43, 10, 872997, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conversationrecipient',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conversationrecipient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 7, 43, 21, 72720, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 7, 43, 29, 687973, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 7, 43, 39, 263966, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 7, 43, 54, 215865, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='friendship',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends_from', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 7, 44, 32, 414797, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 7, 44, 39, 22740, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 7, 44, 47, 71314, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 7, 44, 53, 735739, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskworker',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskworkerresult',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 7, 45, 0, 430179, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 2, 7, 45, 6, 894204, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(through='crowdsourcing.UserLanguage', to='crowdsourcing.Language'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crowdsourcing.City'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='crowdsourcing.Category'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='crowdsourcing.Country'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crowdsourcing.Comment'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversationrecipient',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Conversation'),
        ),
        migrations.AlterField(
            model_name='conversationrecipient',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='crowdsourcing.Region'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='type',
            field=models.IntegerField(choices=[(1, b'Worker'), (2, b'Requester')]),
        ),
        # migrations.AlterField(
        #     model_name='googlecredential',
        #     name='account',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.ExternalAccount'),
        # ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crowdsourcing.Project'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Project'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='crowdsourcing.Project'),
        ),
        migrations.AlterField(
            model_name='qualificationitem',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crowdsourcing.Qualification'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='origin_type',
            field=models.IntegerField(choices=[(1, b'Worker'), (2, b'Requester')]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='crowdsourcing.Skill'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crowdsourcing.Project'),
        ),
        migrations.AlterField(
            model_name='taskworker',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='crowdsourcing.Task'),
        ),
        migrations.AlterField(
            model_name='taskworker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskworkerresult',
            name='task_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='crowdsourcing.TaskWorker'),
        ),
        migrations.AlterField(
            model_name='taskworkerresult',
            name='template_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crowdsourcing.TemplateItem'),
        ),
        migrations.AlterField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crowdsourcing.Template'),
        ),
        migrations.AlterField(
            model_name='templateitemproperties',
            name='template_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='crowdsourcing.TemplateItem'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crowdsourcing.Address'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together=set([('origin', 'target'), ('origin', 'target', 'updated_at', 'origin_type')]),
        ),
        migrations.DeleteModel(
            name='AccountModel',
        ),
        migrations.DeleteModel(
            name='PasswordResetModel',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Message'),
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(through='crowdsourcing.MessageRecipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
