# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 18:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0080_review_time_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='crowdsourcing.Project')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='crowdsourcing.Review')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Worker')),
            ],
        ),
    ]
