# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0081_get_min_ratings_fn'),
        ('crowdsourcing', '0076_get_min_ratings_fn'),
    ]

    operations = [
    ]
