# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0082_get_min_ratings_fn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, b'Draft'), (2, b'Published'), (3, b'In Progress'), (4, b'Completed'), (5, b'Paused')], default=1),
        ),
    ]
