# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0083_auto_20160511_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='crowdsourcing.Requester'),
            preserve_default=False,
        ),
    ]
