# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0084_qualification_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
