# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0086_get_requester_ratings_fn_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='revised_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 6, 21, 15, 53, 889687, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='revision_log',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='revised_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 6, 21, 16, 3, 834231, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='revision_log',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='taskworker',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskworker',
            name='revised_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 6, 21, 16, 14, 466347, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskworker',
            name='revision_log',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='revised_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 6, 21, 16, 25, 562771, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='revision_log',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templateitem',
            name='revised_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 6, 21, 16, 33, 666790, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templateitem',
            name='revision_log',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
