# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0078_merge'),
        ('crowdsourcing', '0086_get_requester_ratings_fn_updated'),
    ]

    operations = [
    ]
