# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0075_auto_20160506_0627'),
        ('crowdsourcing', '0086_get_requester_ratings_fn_updated'),
    ]

    operations = [
    ]
