# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0087_auto_20160606_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskworker',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
