# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 23:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdsourcing', '0087_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesteraccesscontrolgroup',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='workeraccesscontrolentry',
            old_name='created_timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='qualification',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesteraccesscontrolgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 3, 23, 29, 11, 334238, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workeraccesscontrolentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 3, 23, 29, 17, 262749, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualificationitem',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Qualification'),
        ),
        migrations.AlterField(
            model_name='requesteraccesscontrolgroup',
            name='type',
            field=models.SmallIntegerField(choices=[(1, b'allow'), (2, b'deny')], default=1),
        ),
    ]
