# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0088_auto_20160603_2329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='templateitem',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='project',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='revision_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='revision_date',
        ),
        migrations.RemoveField(
            model_name='template',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='template',
            name='revision_date',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='revision_date',
        ),
    ]
