# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0089_auto_20160606_2018'),
        ('crowdsourcing', '0088_auto_20160607_1922'),
    ]

    operations = [
    ]
