# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0088_auto_20160607_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationitem',
            name='next_op',
        ),
        migrations.AlterField(
            model_name='qualificationitem',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crowdsourcing.Qualification'),
        ),
    ]
