# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0089_auto_20160607_0232'),
        ('crowdsourcing', '0091_auto_20160607_2013'),
    ]

    operations = [
    ]
