# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0091_auto_20160607_2013'),
        ('crowdsourcing', '0088_auto_20160606_2123'),
        ('crowdsourcing', '0077_auto_20160505_0522'),
        ('crowdsourcing', '0088_auto_20160603_2329'),
    ]

    operations = [
    ]
