# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0092_merge'),
        ('crowdsourcing', '0092_auto_20160608_0236'),
    ]

    operations = [
    ]
