# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0092_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateitem',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='revised_at',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='revision_log',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=b'Untitled Project', error_messages={b'required': b'Please enter the project name!'}, max_length=256),
        ),
        migrations.AlterField(
            model_name='qualificationitem',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crowdsourcing.Qualification'),
        ),
    ]
