# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0094_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
