# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0095_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='relaunch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='qualificationitem',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crowdsourcing.Qualification'),
        ),
    ]
