# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0096_auto_20160614_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='include_next',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='relaunch',
            field=models.BooleanField(default=False),
        ),
    ]
