# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0097_auto_20160614_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateitem',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='revised_at',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='revision_log',
        ),
    ]
