# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0098_city_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
