# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0099_auto_20160627_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[(b'white', b'White'), (b'hispanic', b'Hispanic'), (b'black', b'Black'), (b'islander', b'Native Hawaiian or Other Pacific Islander'), (b'indian', b'Indian'), (b'asian', b'Asian'), (b'native', b'Native American or Alaska Native'), (b'mixed', b'Mixed Race'), (b'other', b'Other')], max_length=8, null=True),
        ),
    ]
