# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0100_remove_task_relaunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='row_number',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskworker',
            name='status',
            field=models.IntegerField(choices=[(1, b'In Progress'), (2, b'Submitted'), (3, b'Accepted'), (4, b'Rejected'), (5, b'Returned'), (6, b'Skipped'), (7, b'Expired')], db_index=True, default=1),
        ),
    ]
