# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0078_auto_20160503_2130'),
        ('crowdsourcing', '0101_auto_20160616_1708'),
    ]

    operations = [
    ]
