# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0102_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccount',
            name='type',
            field=models.IntegerField(choices=[(1, b'Worker'), (2, b'Requester'), (3, b'Escrow')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_type',
            field=models.SmallIntegerField(choices=[(1, b'self'), (2, b'project_owner')], default=1),
        ),
    ]
