# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0103_auto_20160616_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='include_next',
        ),
        migrations.AddField(
            model_name='project',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='task',
            name='exclude_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crowdsourcing.Task'),
        ),
    ]
