# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0104_auto_20160623_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exclude_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excluded_tasks', to='crowdsourcing.Project'),
        ),
    ]
