# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0100_auto_20160627_2213'),
        ('crowdsourcing', '0108_remove_templateitem_deleted_at'),
    ]

    operations = [
    ]
