# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0110_auto_20160630_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task_time',
        ),
    ]
