# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-01 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0112_project_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='timeout',
        ),
    ]
