# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-01 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0113_remove_project_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timeout',
            field=models.DurationField(null=True),
        ),
    ]
