# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0114_project_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='task_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.TaskWorker'),
        ),
    ]
