# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0114_project_timeout'),
        ('crowdsourcing', '0109_merge'),
    ]

    operations = [
    ]
