# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0115_rating_task_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='task_worker',
        ),
        migrations.AddField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Project'),
        ),
    ]
