# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0115_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReviewMatchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_worker', to='crowdsourcing.TaskWorker')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_worker', to='crowdsourcing.TaskWorker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrueSkillScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mu', models.FloatField()),
                ('sigma', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
