# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0116_peerreviewmatchup_trueskillscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerreviewmatchup',
            name='first',
        ),
        migrations.RemoveField(
            model_name='peerreviewmatchup',
            name='second',
        ),
        migrations.AddField(
            model_name='peerreviewmatchup',
            name='left',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='left_worker', to='crowdsourcing.TaskWorker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreviewmatchup',
            name='left_mu',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreviewmatchup',
            name='left_sigma',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreviewmatchup',
            name='right',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='right_worker', to='crowdsourcing.TaskWorker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreviewmatchup',
            name='right_mu',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreviewmatchup',
            name='right_sigma',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
