# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0116_auto_20160705_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks_in_progress',
            field=models.IntegerField(default=0),
        ),
    ]
