# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0117_auto_20160727_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='review_price',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
