# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0117_auto_20160720_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trueskillscore',
            name='worker',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='worker_score', to='crowdsourcing.TaskWorker'),
            preserve_default=False,
        ),
    ]
