# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0118_auto_20160720_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreviewmatchup',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_matchup', to='crowdsourcing.TaskWorker'),
        ),
        migrations.AlterField(
            model_name='peerreviewmatchup',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_matchup', to='crowdsourcing.TaskWorker'),
        ),
    ]
