# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0118_project_review_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_reviewed',
        ),
        migrations.AddField(
            model_name='project',
            name='has_review',
            field=models.BooleanField(default=False),
        ),
    ]
