# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0118_project_rating_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='min_rating',
            field=models.FloatField(default=3.0),
        ),
    ]
