# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0119_auto_20160720_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trueskillscore',
            name='worker',
        ),
    ]
