# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0119_auto_20160728_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprojectscore',
            name='task_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.TaskWorker'),
        ),
    ]
