# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdsourcing', '0120_auto_20160719_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRatingFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(default=0)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_feedback', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rawratingfeedback',
            unique_together=set([('requester', 'worker', 'task')]),
        ),
    ]
