# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-29 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0121_remove_workerprojectscore_task_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='review_price',
        ),
    ]
