# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0122_auto_20160725_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Batch'),
        ),
    ]
