# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0122_remove_project_review_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprojectscore',
            name='project',
        ),
        migrations.AddField(
            model_name='workerprojectscore',
            name='project_group_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
