# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0123_batch_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='run_key',
            new_name='rerun_key',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='deleted_at',
        ),
    ]
