# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0126_boomeranglog_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boomeranglog',
            old_name='project_id',
            new_name='project',
        ),
    ]
