# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0127_auto_20160803_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_api_only',
            field=models.BooleanField(default=True),
        ),
    ]
