# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0128_project_is_api_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hash',
            field=models.CharField(db_index=True, default='4a0c71ed4193c5c2c33dee7cb77595a7d59e2993812fd96c1592af9a6db6739f', max_length=64),
            preserve_default=False,
        ),
    ]
