# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0123_auto_20160802_1955'),
        ('crowdsourcing', '0128_project_is_api_only'),
    ]

    operations = [
    ]
