# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0128_project_is_api_only'),
        ('crowdsourcing', '0116_peerreviewmatchup_trueskillscore'),
    ]

    operations = [
    ]
