# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0129_task_hash'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='task',
            index_together=set([('rerun_key', 'hash')]),
        ),
    ]
