# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0129_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermatchscore',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='crowdsourcing.Project'),
            preserve_default=False,
        ),
    ]
