# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0130_workermatchscore_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermatchscore',
            name='project',
        ),
        migrations.AddField(
            model_name='workermatchscore',
            name='project_group_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
