# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0131_auto_20160818_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermatchscore',
            name='project_group_id',
        ),
        migrations.AddField(
            model_name='workermatchscore',
            name='project_score',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='crowdsourcing.WorkerProjectScore'),
            preserve_default=False,
        ),
    ]
