# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0131_error'),
        ('crowdsourcing', '0132_auto_20160818_2206'),
    ]

    operations = [
    ]
