# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 23:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0132_auto_20160822_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unspecified_responses',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
