# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0133_userprofile_unspecified_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='purpose_of_use',
            field=models.CharField(blank=True, choices=[(b'professional', b'Professional'), (b'personal', b'personal'), (b'research', b'research'), (b'other', b'other')], max_length=64, null=True),
        ),
    ]
