# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0134_userprofile_purpose_of_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawratingfeedback',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterIndexTogether(
            name='rawratingfeedback',
            index_together=set([('requester', 'worker', 'task', 'is_excluded')]),
        ),
    ]
