# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0134_auto_20160822_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchgroup',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_group', to='crowdsourcing.Batch'),
            preserve_default=False,
        ),
    ]
