# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0135_matchgroup_batch'),
        ('crowdsourcing', '0135_auto_20160824_0348'),
    ]

    operations = [
    ]
