# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0135_auto_20160824_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveRejection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('reason', models.IntegerField(choices=[(1, b'Pays very poorly'), (2, b'Offensive or inappropriate content'), (3, b'Other')])),
                ('detail', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, b'Draft'), (2, b'Published'), (3, b'In Progress'), (4, b'Completed'), (5, b'Paused'), (6, b'Rejected')], default=1),
        ),
        migrations.AddField(
            model_name='taskworker',
            name='collective_rejection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.CollectiveRejection'),
        ),
    ]
