# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdsourcing', '0135_auto_20160824_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_group', to='crowdsourcing.Batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerMatchScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mu', models.FloatField()),
                ('sigma', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerProjectScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_group_id', models.IntegerField()),
                ('mu', models.FloatField(default=25.0)),
                ('sigma', models.FloatField(default=8.333)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workermatchscore',
            name='project_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='crowdsourcing.WorkerProjectScore'),
        ),
        migrations.AddField(
            model_name='workermatchscore',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='crowdsourcing.TaskWorker'),
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='crowdsourcing.MatchGroup'),
        ),
        migrations.AddField(
            model_name='match',
            name='worker_match_scores',
            field=models.ManyToManyField(to='crowdsourcing.WorkerMatchScore'),
        ),
    ]
