# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0136_auto_20160830_0621'),
        ('crowdsourcing', '0136_auto_20160829_2213'),
    ]

    operations = [
    ]
