# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0138_auto_20160831_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchgroup',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_groups', to='crowdsourcing.MatchGroup'),
        ),
    ]
