# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0139_matchgroup_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mu', models.FloatField(default=25.0)),
                ('sigma', models.FloatField(default=25.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='match',
            name='worker_match_scores',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.IntegerField(choices=[(1, b'Created'), (2, b'Completed')], default=1),
        ),
        migrations.AddField(
            model_name='matchworker',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='crowdsourcing.Match'),
        ),
        migrations.AddField(
            model_name='matchworker',
            name='task_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='crowdsourcing.TaskWorker'),
        ),
    ]
