# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0140_auto_20160902_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchworker',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='matchworker',
            name='mu',
            field=models.FloatField(default=25.0, null=True),
        ),
        migrations.AlterField(
            model_name='matchworker',
            name='sigma',
            field=models.FloatField(default=25.0, null=True),
        ),
    ]
