# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0141_auto_20160904_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='crowdsourcing.Task'),
        ),
        migrations.AddField(
            model_name='matchworker',
            name='old_mu',
            field=models.FloatField(default=25.0, null=True),
        ),
        migrations.AddField(
            model_name='matchworker',
            name='old_sigma',
            field=models.FloatField(default=8.333, null=True),
        ),
        migrations.AlterField(
            model_name='matchworker',
            name='mu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='matchworker',
            name='sigma',
            field=models.FloatField(null=True),
        ),
    ]
