# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0142_auto_20160904_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchworker',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='match',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
