# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0144_task_min_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='previous_min_rating',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='task',
            name='rating_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
