# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0145_auto_20160909_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boomeranglog',
            name='project',
        ),
        migrations.AddField(
            model_name='boomeranglog',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boomeranglog',
            name='object_type',
            field=models.CharField(default=b'project', max_length=8),
        ),
    ]
