# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0148_auto_20170120_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='target',
        ),
        migrations.RemoveField(
            model_name='paypalflow',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='paypalpayoutlog',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paypal_email',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='PayPalFlow',
        ),
        migrations.DeleteModel(
            name='PayPalPayoutLog',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
