# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 23:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0151_auto_20161013_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeTransferReversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(db_index=True, max_length=128)),
                ('stripe_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversals', to='crowdsourcing.StripeTransfer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='striperefund',
            name='charge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='crowdsourcing.StripeCharge'),
            preserve_default=False,
        ),
    ]
