# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0151_taskworker_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworker',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
