# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0152_auto_20161013_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecharge',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecharge',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripecharge',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskworker',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.StripeCharge'),
        ),
        migrations.AddField(
            model_name='taskworker',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
    ]
