# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0153_auto_20161023_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='available_balance',
            field=models.IntegerField(default=0),
        ),
    ]
