# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0154_stripecustomer_available_balance'),
        ('crowdsourcing', '0152_taskworker_started_at'),
    ]

    operations = [
    ]
