# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0156_auto_20170404_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
