# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0158_userprofile_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(db_index=True, default=None, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
