# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0159_auto_20170509_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
