# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0160_auto_20170511_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_opened_at',
            field=models.DateTimeField(null=True),
        ),
    ]
