# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-19 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0163_taskworker_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskworker',
            name='submitted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
