# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0164_auto_20170519_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted_at',
        ),
    ]
