# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0166_auto_20170522_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecharge',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripecharge',
            name='raw_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
