# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0167_auto_20170523_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecharge',
            name='discount',
            field=models.FloatField(default=1.0),
        ),
    ]
