# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0168_stripecharge_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_price_per_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='task_price_field',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
