# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0170_task_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='discussion_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
