# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0171_project_discussion_link'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='dropboxauth',
        #     name='user',
        # ),
        # migrations.DeleteModel(
        #     name='DropboxAuth',
        # ),
    ]
