# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0172_auto_20170601_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalaccount',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='googleauth',
            name='id',
        ),
        migrations.RemoveField(
            model_name='googlecredential',
            name='account',
        ),
        migrations.DeleteModel(
            name='ExternalAccount',
        ),
        migrations.DeleteModel(
            name='GoogleAuth',
        ),
        migrations.DeleteModel(
            name='GoogleCredential',
        ),
    ]
