# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0174_auto_20170602_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('valid_from', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
