# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 18:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0174_auto_20170602_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aux_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
