# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-10 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0175_registrationwhitelist'),
        ('crowdsourcing', '0175_auto_20170606_1822'),
    ]

    operations = [
    ]
