# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0176_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnfeedback',
            name='notification_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='returnfeedback',
            name='notification_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
