# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0177_auto_20170614_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationitem',
            name='scope',
            field=models.CharField(db_index=True, default=b'project', max_length=32),
        ),
    ]
