# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0178_qualificationitem_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworker',
            name='is_qualified',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
