# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0178_workerbonus'),
        ('crowdsourcing', '0179_taskworker_is_qualified'),
    ]

    operations = [
    ]
