# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0181_workerbonus_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerbonus',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
