# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0183_auto_20170627_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresponse',
            name='hash_sha512',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fileresponse',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='type',
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
