# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-30 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0184_auto_20170627_2215'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='stripecharge',
            index_together=set([('created_at',), ('created_at', 'customer')]),
        ),
    ]
