# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 20:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0185_auto_20170630_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aux_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={b'sort_results_by': b'worker_id'}, null=True),
        ),
    ]
