# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 00:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0185_auto_20170630_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='aux_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
