# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0186_auto_20170707_2049'),
        ('crowdsourcing', '0186_userpreferences_aux_attributes'),
    ]

    operations = [
    ]
