# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0187_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworker',
            name='returned_at',
            field=models.DateTimeField(null=True),
        ),
    ]
