# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mturknotification',
            name='data',
        ),
        migrations.AddField(
            model_name='mturknotification',
            name='assignment_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='mturknotification',
            name='event_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='mturknotification',
            name='hit_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='mturknotification',
            name='hit_type_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
