# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0002_mturk_worker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mturkhit',
            unique_together=set([]),
        ),
    ]
