# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 05:21
from __future__ import unicode_literals

from django.db import migrations
from crowdsourcing.utils import generate_random_id


def create_mturk_user(apps, schema_editor):
    user = apps.get_model("auth", "User")
    profile = apps.get_model("crowdsourcing", "UserProfile")
    worker = apps.get_model("crowdsourcing", "Worker")
    mturk_user = user.objects.create_user(is_active=False, username='mturk', email='mturk.worker@daemo.stanford.edu',
                                          password=generate_random_id())
    mturk_profile = profile.objects.get_or_create(user=mturk_user)
    mturk_worker = worker.objects.get_or_create(profile=mturk_profile[0])


class Migration(migrations.Migration):
    dependencies = [
        ('mturk', '0003_auto_20160118_1650'),
    ]

    operations = [
        migrations.RunPython(create_mturk_user),
    ]
