# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mturk', '0003_auto_20160629_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='mturkhittype',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mturk_hit_types', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mturkhittype',
            name='qualifications_mask',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mturkhittype',
            name='boomerang_threshold',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mturkqualification',
            name='auto_granted_value',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mturkqualification',
            unique_together=set([('owner', 'flag')]),
        ),
    ]
