# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0004_mturknotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mturkassignment',
            name='worker_id',
        ),
    ]
