# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0012_auto_20160107_0521'),
        ('mturk', '0004_mturk_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mturkassignment',
            name='task_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mturk_assignments', to='crowdsourcing.TaskWorker'),
        ),
        migrations.AlterField(
            model_name='mturkassignment',
            name='status',
            field=models.IntegerField(choices=[(1, b'In Progress'), (2, b'Submitted'), (3, b'Accepted'), (4, b'Rejected'), (5, b'Returned'), (6, b'Skipped')], default=1),
        ),
    ]
