# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0005_auto_20160629_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mturkhit',
            name='hit_type_id',
        ),
        migrations.AddField(
            model_name='mturkhit',
            name='hit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mturk.MTurkHITType'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mturkqualification',
            unique_together=set([('owner', 'flag', 'name')]),
        ),
    ]
