# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0006_auto_20160706_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTurkWorkerQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.CharField(max_length=32)),
                ('score', models.IntegerField(default=1)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mturk.MTurkQualification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
