# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0007_mturkworkerqualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mturkhittype',
            name='boomerang_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mturk.MTurkQualification'),
        ),
        migrations.AddField(
            model_name='mturkworkerqualification',
            name='overwritten',
            field=models.BooleanField(default=False),
        ),
    ]
