# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0008_auto_20160130_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mturkhit',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mturk_hit', to='crowdsourcing.Task'),
        ),
    ]
