# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0008_auto_20160708_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='mturkqualification',
            name='is_blacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mturkqualification',
            name='lower_bound',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='mturkqualification',
            name='upper_bound',
            field=models.FloatField(default=3.0),
        ),
    ]
