# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0009_auto_20160809_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mturkqualification',
            name='lower_bound',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='mturkqualification',
            name='upper_bound',
            field=models.IntegerField(default=300),
        ),
    ]
