# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0010_mturkaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mturkaccount',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
