# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0010_auto_20160809_0231'),
        ('mturk', '0002_auto_20160708_2209'),
    ]

    operations = [
    ]
