# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0010_auto_20160809_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mturkhit',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Completed'), (3, 'Expired'), (4, 'Deleted')], default=1),
        ),
    ]
