# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 18:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0011_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mturknotification',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='mturknotification',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='mturknotification',
            name='hit_id',
        ),
        migrations.RemoveField(
            model_name='mturknotification',
            name='hit_type_id',
        ),
        migrations.AddField(
            model_name='mturknotification',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
