# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0011_mturkaccount_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mturkassignment',
            name='status',
            field=models.IntegerField(choices=[(1, b'In Progress'), (2, b'Submitted'), (3, b'Accepted'), (4, b'Rejected'), (5, b'Returned'), (6, b'Skipped'), (7, b'Expired')], default=1),
        ),
    ]
