TASK_ACCEPTED = 'CREATED'
TASK_SUBMITTED = 'SUBMITTED'
TASK_APPROVED = 'APPROVED'
TASK_RETURNED = 'RETURNED'
TASK_REJECTED = 'REJECTED'
TASK_EXPIRED = 'EXPIRED'
TASK_SKIPPED = 'SKIPPED'

ACTION_GROUPADD = 'GROUPADD'
